services:
  genjishimada-web:
    container_name: genjishimada-web
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=${APP_DEBUG}
      - APP_URL=${APP_URL}
      - APP_KEY=${APP_KEY}
      - LOG_CHANNEL=${LOG_CHANNEL}
      - LOG_STACK=${LOG_STACK}
      - LOG_DEPRECATIONS_CHANNEL=${LOG_DEPRECATIONS_CHANNEL}
      - LOG_LEVEL=${LOG_LEVEL}
      - X_API_ROOT=${X_API_ROOT}
      - X_API_VERIFY=${X_API_VERIFY}
      - X_API_KEY=${X_API_KEY}
      - DISCORD_REDIRECT_URI=${DISCORD_REDIRECT_URI}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
      - DISCORD_MODERATOR_ROLE_IDS=${DISCORD_MODERATOR_ROLE_IDS}
      - TENOR_API_KEY=${TENOR_API_KEY}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - TRANSLATION_API_ROOT=${TRANSLATION_API_ROOT}
      - TRANSLATION_API_KEY=${TRANSLATION_API_KEY}
      - TRANSLATION_API_VERIFY=${TRANSLATION_API_VERIFY}
      - SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT}
      - SENTRY_DSN=${SENTRY_DSN}
      - SENTRY_TUNNEL_ALLOWED_DSN=${SENTRY_TUNNEL_ALLOWED_DSN}
      - SENTRY_TRACES_SAMPLE_RATE=${SENTRY_TRACES_SAMPLE_RATE}
      - SENTRY_PROFILES_SAMPLE_RATE=${SENTRY_PROFILES_SAMPLE_RATE}
      - VITE_APP_ENV=${VITE_APP_ENV}
      - VITE_APP_RELEASE=${VITE_APP_RELEASE}
      - VITE_SENTRY_DSN=${VITE_SENTRY_DSN}
      - SESSION_SECURE_COOKIE=${SESSION_SECURE_COOKIE}
      - SESSION_DOMAIN=${SESSION_DOMAIN}
      - REDIRECT_URL_LOCAL=${REDIRECT_URL_LOCAL}
      - REDIRECT_URL_TEST=${REDIRECT_URL_TEST}
      - REDIRECT_URL_PROD=${REDIRECT_URL_PROD}

    networks:
      - genji-network

networks:
  genji-network:
    external: true
